version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: semillero_digital
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: